### ISSUE TITLE
no longer works on github actions...

### ISSUE THREAD

**Issue by mephmanx** [dtinth/obtain-github-app-installation-access-token#5]
Things run locally but I get this error when run on github actions...

This is all Im running with the var being a secret.

echo "$(npx obtain-github-app-installation-access-token ci $GH_APP_CREDENTIALS_TOKEN)" > ...

obtain-github-app-installation-access-token ci <token>
[1567](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1568)
Obtains a GitHub App Installation Token from Base64-encoded credentials token
[1568](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1569)
Options:
[1569](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1570)
  --version  Show version number                                       [boolean]
[1570](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1571)
  --help     Show help                                                 [boolean]
[1571](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1572)
  --token    Base64-encoded of JSON object with { appId, installationId,
[1572](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1573)
             privateKey }                                    [string] [required]
[1573](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1574)
SyntaxError: Unexpected token � in JSON at position 0
[1574](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1575)
    at JSON.parse (<anonymous>)
[1575](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1576)
    at /home/runner/.npm/_npx/45779/lib/node_modules/obtain-github-app-installation-access-token/src/main.ts:52:28
[1576](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1577)
    at Generator.next (<anonymous>)
[1577](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1578)
    at /home/runner/.npm/_npx/45779/lib/node_modules/obtain-github-app-installation-access-token/dist/index.js:2123:71
[1578](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1579)
    at new Promise (<anonymous>)
[1579](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1580)
    at module.exports.131.__awaiter (/home/runner/.npm/_npx/45779/lib/node_modules/obtain-github-app-installation-access-token/dist/index.js:2119:12)
[1580](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1581)
    at Object.handler (/home/runner/.npm/_npx/45779/lib/node_modules/obtain-github-app-installation-access-token/src/main.ts:51:20)
[1581](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1582)
    at Object.runCommand (/home/runner/.npm/_npx/45779/lib/node_modules/obtain-github-app-installation-access-token/node_modules/yargs/lib/command.js:242:1)
[1582](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1583)
    at Object.parseArgs [as _parseArgs] (/home/runner/.npm/_npx/45779/lib/node_modules/obtain-github-app-installation-access-token/dist/index.js:23188:30)
[1583](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1584)
    at Object.parse (/home/runner/.npm/_npx/45779/lib/node_modules/obtain-github-app-installation-access-token/dist/index.js:22652:19)
[1584](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1585)
! First copy your one-time code: 7BCE-38C2
[1585](https://github.com/dotcomrow/gateway-machine-build/actions/runs/4049312118/jobs/6965531891#step:11:1586)
Open this URL to continue in your web browser: https://github.com/login/device

**Comment by dtinth** [comment]
On line 1573 it says: **SyntaxError: Unexpected token � in JSON at position 0**

It seems like there is some invalid JSON inside the `GH_APP_CREDENTIALS_TOKEN` secret.

**Comment by mephmanx** [comment]
I ended up doing a lot of digging and it turned out to be an issue on my end.  Thank you for responding!

**Comment by dtinth** [comment]
Glad you resolved the problem. Cheers!
